// ----------------------------------------------------------------
// [檔案] map_data.js (V3.0 - 2026-09-06 縮編)
// 職責：奧瑞亞預設世界的分區與地點。83 格縮成 49 格：留下的每一格都要「一般身分進得去、主角群有人會去、去了能發生事」；
//       基礎設施、官方機密、犯罪目錄一律不放地圖上（留在世界書當背景）。補了 F 蒸穹港域、G 幻冠天城。
//       每格帶 desc（什麼地方／什麼時段／去的理由）與 regulars（誰會來），餵給「探索此地」與排程引擎，探索不必再憑空造人。
//       完整的盤點理由見 tmp/map_facility_audit.md（本地）。
// ----------------------------------------------------------------
(function() {
    console.log('[PhoneOS] 載入奧瑞亞地圖數據庫 (V3.0)...');

    const AUREALIS_DB = {
        'A': {
            name: 'Solarium 日暉區',
            background: 'https://raw.githubusercontent.com/nancywang3641/sound-files/main/aseets/location_img/A區_日暉區.jpg',
            facilities: {
                'Stellar_Nexus': { sceneId: 'A_Stellar_Nexus', name: 'Stellar Nexus 總部', icon: '🏢', shortName: '總部', className: 'facility-stellar', characters: [],
                    imageUrl: 'https://raw.githubusercontent.com/nancywang3641/sound-files/main/aseets/location_img/A區_Stellar_Nexus.jpeg',
                    desc: '73 層科技總部，50 層以上要雙重驗證。上班日全天有人，深夜常剩白則一人；訪客在一樓大廳等，沒證進不了電梯。',
                    regulars: ['雷伊·洛爾德', '艾沙·洛爾德', '肯斯頓·肯特', '白則·貝爾德', '艾迪·克特羅斯', '偉特·默瑟', '維茲·韓', '劉梓欣', '蘇景明', '丹尼爾·卡萊爾'] },
                'Lumen_Loop': { sceneId: 'A_Lumen_Loop', name: 'Lumen Loop 轉運中樞站', icon: '🚇', shortName: '轉運站', className: 'facility-lumen-loop', characters: [],
                    imageUrl: 'https://raw.githubusercontent.com/nancywang3641/sound-files/main/aseets/location_img/A區_LumenLoop_轉運中樞站.jpeg',
                    desc: '空軌樞紐，通 B、D、G 三區，十分鐘一班。早晚尖峰擠滿上班族，深夜只剩夜班與醉鬼。跨區必經、最容易撞見人的地方。',
                    regulars: ['所有人'] },
                'Orion_Global': { sceneId: 'A_Orion_Global', name: '獵戶金融塔', icon: '🌍', shortName: '金融塔', className: 'facility-orion', characters: [],
                    imageUrl: 'https://raw.githubusercontent.com/nancywang3641/sound-files/main/aseets/location_img/A區_OrionGlobal.jpeg',
                    desc: '洛爾德 OGH 總部，65 層，50 層以上家族專屬。雷伊被父親召回談判的地方；沒有預約連一樓咖啡廳都進不去。',
                    regulars: ['威廉·洛爾德', '亞歷克斯·洛爾德', '馬庫斯·洛爾德', '雷伊·洛爾德'] },
                'Solaris_Apex': { sceneId: 'A_Solaris_Apex', name: '日耀尖塔', icon: '🌟', shortName: '尖塔', className: 'facility-solaris', characters: [],
                    imageUrl: 'https://raw.githubusercontent.com/nancywang3641/sound-files/main/aseets/location_img/A區_Solaris_Apex.jpeg',
                    desc: '320 米最高建築，AC 財閥聯盟的中樞。平時只是天際線上的一座塔，一般人到不了理事會樓層；AC 會議、家族峻會的劇情才會開門。',
                    regulars: ['各家家主', '亞瑟·洛爾德', '威爾弗雷德·卡萊爾'] },
                'Commerce_District': { sceneId: 'A_Commerce_District', name: '商業街區', icon: '🏬', shortName: '商業街', className: 'facility-commerce', characters: [],
                    imageUrl: 'https://raw.githubusercontent.com/nancywang3641/sound-files/main/aseets/location_img/A區_MYCIA_商場.jpeg',
                    desc: '總部樓下的商場、轉運站商圈、商務餐廳。平日午休與下班時段最熱，週末反而空。SN 的人午餐、應酬都在這一帶。',
                    regulars: ['SN 全員', '艾薇'] },
            }
        },
        'B': {
            name: 'Nocturne 夜韻街區',
            background: 'https://raw.githubusercontent.com/nancywang3641/sound-files/main/aseets/char_home/B%E5%8D%80_%E5%A4%9C%E9%9F%BB%E8%A1%97%E5%8D%80.jpg',
            facilities: {
                'LUXA_DOME': { sceneId: 'B_LUXA_DOME', name: 'LUXA 路克薩巨蛋', icon: '🎭', shortName: '巨蛋', className: 'facility-luxa', characters: [],
                    imageUrl: 'https://raw.githubusercontent.com/nancywang3641/sound-files/main/aseets/location_img/B區_LUXA_DOME_路克薩巨蛋.jpeg',
                    desc: '直徑兩百米、三萬五千人的演出場館，月均十幾場演出。有演出的晚上整區塞車；散場後人潮流進夜市與 24 號街。',
                    regulars: ['費利克斯·貝爾德', '林旭南', '放養群（看演出）'] },
                'NOVA_Mall': { sceneId: 'B_NOVA_Mall', name: 'NOVA 百貨環廊', icon: '🛒', shortName: '百貨', className: 'facility-nova-mall', characters: [],
                    imageUrl: 'https://raw.githubusercontent.com/nancywang3641/sound-files/main/aseets/location_img/B區_NOVA_百貨環廊.jpeg',
                    desc: '環形五層、兩百家店，潮牌、科技、餐飲，24 小時營業。艾迪的購物慾在這裡燒錢，深夜四樓科技層常有人在試新玩具。',
                    regulars: ['艾迪·克特羅斯', '艾薇', '白星澤'] },
                'Decibel_Ruins': { sceneId: 'B_Decibel_Ruins', name: '聲波廢墟俱樂部', icon: '🎵', shortName: '俱樂部', className: 'facility-decibel', characters: [],
                    imageUrl: 'https://raw.githubusercontent.com/nancywang3641/sound-files/main/aseets/location_img/B區_聲波廢墟俱樂部.jpeg',
                    desc: '廢棄倉庫改的地下俱樂部，三個舞池，午夜後才開。放養群的夜晚在這裡開始或結束；亦楷偶爾在這演出。',
                    regulars: ['丹尼爾·卡萊爾', '黎昂·維斯頓', 'Zephyr Locke', '方亦楷', '卡門·羅斯'] },
                'Graffiti_Buildings': { sceneId: 'B_Graffiti_Buildings', name: '藝術街區', icon: '🎨', shortName: '藝術街', className: 'facility-graffiti', characters: [],
                    imageUrl: 'https://raw.githubusercontent.com/nancywang3641/sound-files/main/aseets/location_img/B區_塗鴉樓群.jpeg',
                    desc: '十棟塗鴉樓、五十米脈衝牆、五百座的小劇院，創作者聚落。下午到深夜都有人，白天是工作室、晚上變成街頭表演與小型展。',
                    regulars: ['方亦楷', '瓦倫丁·聖詹姆斯', '艾迪·克特羅斯'] },
                'B_Street_24': { sceneId: 'B_B_Street_24', name: '24號街', icon: '🏠', shortName: '24號街', className: 'facility-b-street', characters: [],
                    imageUrl: 'https://raw.githubusercontent.com/nancywang3641/sound-files/main/aseets/location_img/B區_B街24.jpeg',
                    desc: '24 小時不關的一條街：深夜食堂、酒吧、便利店、餐飲街。凌晨兩點還能吃到熱的，放養群收工後和 SN 加班後都會落在這裡。',
                    regulars: ['放養群', '蘇景明', '偉特·默瑟'] },
                'Night_Market': { sceneId: 'B_Night_Market', name: '夜市核心區', icon: '🌃', shortName: '夜市', className: 'facility-night-market', characters: [],
                    imageUrl: 'https://raw.githubusercontent.com/nancywang3641/sound-files/main/aseets/location_img/B區_夜市核心區.jpeg',
                    desc: '兩百個攤位，傍晚六點到凌晨兩點。B 區最有人味的地方，吃、逛、撞見熟人；羅德在這裡直播帶貨過。',
                    regulars: ['陳彥庭', '許萊特', '羅德·洛爾德', '黎昂·維斯頓'] },
                'Nocturne_Arena': { sceneId: 'B_Nocturne_Arena', name: '拳館', icon: '🏟️', shortName: '拳館', className: 'facility-arena', characters: [],
                    imageUrl: 'https://raw.githubusercontent.com/nancywang3641/sound-files/main/aseets/location_img/B區_Nocturne Arena_夜韻競技館.jpeg',
                    desc: '夜韻競技館裡的拳擊與格鬥場，晚上有業餘賽。黎昂打拳、鳴野來打架，丹坐最後一排看戲。',
                    regulars: ['黎昂·維斯頓', '陸鳴野', '丹尼爾·卡萊爾'] },
                'Nocturne_Police': { sceneId: 'B_Nocturne_Police', name: '公安分局', icon: '👮', shortName: '公安', className: 'facility-police', characters: [],
                    imageUrl: 'https://raw.githubusercontent.com/nancywang3641/sound-files/main/aseets/location_img/B區_Nocturne_公安分局.jpeg',
                    desc: 'B 區的分局，夜裡最忙。黎昂被拘留就是關在這裡，馬修永遠第一個到、罵最狠、衝最快；莉安娜負責事後收拾。',
                    regulars: ['黎昂·維斯頓', '馬修·維斯頓', '莉安娜·維斯頓', 'Zephyr Locke'] },
                'Residential_Zone': { sceneId: 'B_Residential_Zone', name: '高層公寓', icon: '🏘️', shortName: '高層公寓', className: 'facility-residential-zone', characters: [],
                    imageUrl: 'https://raw.githubusercontent.com/nancywang3641/sound-files/main/aseets/location_img/B區_艾迪_創意青年公寓.jpeg',
                    desc: 'B 區的創意公寓與時尚公寓，月租從幾千到幾萬都有。亦楷住這裡，彥庭下班常來；夜裡樓下就是夜生活。',
                    regulars: ['方亦楷', '陳彥庭', '卡門·羅斯'] },
            }
        },
        'C': {
            name: 'Horizon 地平綠域',
            background: 'https://raw.githubusercontent.com/nancywang3641/sound-files/main/aseets/location_img/C區_地平綠域.jpg',
            facilities: {
                'Civic_Hall': { sceneId: 'C_Civic_Hall', name: '公民廳', icon: '🏛️', shortName: '公民廳', className: 'facility-civic', characters: [],
                    imageUrl: 'https://raw.githubusercontent.com/nancywang3641/sound-files/main/aseets/location_img/C區_CivicHall_公民厅.jpeg',
                    desc: '六層的市政服務中心，辦身分登記、證照、投訴。白天排隊，五點關門。諾亞·肯特生前在這一帶做調解，喬納森偶爾還會來。',
                    regulars: ['平民角色', '喬納森·肯特', '肯斯頓·肯特'] },
                'Horizon_Medical': { sceneId: 'C_Horizon_Medical', name: '綜合醫院', icon: '🏥', shortName: '醫院', className: 'facility-horizon-medical', characters: [],
                    imageUrl: 'https://raw.githubusercontent.com/nancywang3641/sound-files/main/aseets/location_img/C區_C-Med_綜合醫院.jpeg',
                    desc: 'C 區主要醫院，十二層三百床，急診 24 小時。平民看病的地方，放養群打架受傷會被送來這裡而不是守望塔。',
                    regulars: ['陳彥庭', '許萊特', '受傷的放養群'] },
                'Central_Library': { sceneId: 'C_Central_Library', name: '中央圖書館', icon: '📚', shortName: '圖書館', className: 'facility-central-library', characters: [],
                    imageUrl: 'https://raw.githubusercontent.com/nancywang3641/sound-files/main/aseets/location_img/C區_地平綠域.jpg',
                    desc: '公立主館，五層、兩百個自習座、免費借閱。考試季擠滿學生；天凌躲他媽電話的地方之一。',
                    regulars: ['許萊特', '盧卡斯·貝爾德', '雲天凌'] },
                'Light_Square': { sceneId: 'C_Light_Square', name: '光語廣場', icon: '✨', shortName: '光語', className: 'facility-light-square', characters: [],
                    imageUrl: 'https://raw.githubusercontent.com/nancywang3641/sound-files/main/aseets/location_img/C區_光語廣場.jpeg',
                    desc: '赫柏噴泉所在的中央廣場，連著綠映回廊與社區活動中心。市民集會、小演出、約人見面的預設地點，傍晚最熱鬧。',
                    regulars: ['所有人'] },
                'Daily_Market': { sceneId: 'C_Daily_Market', name: '市集與炸雞店', icon: '🛒', shortName: '市集', className: 'facility-daily-market', characters: [],
                    imageUrl: 'https://raw.githubusercontent.com/nancywang3641/sound-files/main/aseets/location_img/C區_日常市集角.jpeg',
                    desc: '日常市集角，菜攤、小吃、彥庭上班的炸雞店就在轉角。飯點最忙，放養群蹭飯的固定地點。',
                    regulars: ['陳彥庭', '方亦楷', '放養群'] },
                'Council_Hall': { sceneId: 'C_Council_Hall', name: '市議會', icon: '🏛️', shortName: '議會', className: 'facility-council', characters: [],
                    imageUrl: 'https://raw.githubusercontent.com/nancywang3641/sound-files/main/aseets/location_img/C區_地平議會館.jpeg',
                    desc: '地平議會館，市議會開會與議員辦公的地方。林宗翰坐鎮、林語晴在這裡練刀；肯特來這裡替各家打點政商關係。',
                    regulars: ['林宗翰', '林語晴', '肯斯頓·肯特', '喬納森·肯特'] },
                'Education_District': { sceneId: 'C_Education_District', name: '大學區', icon: '🎓', shortName: '大學區', className: 'facility-education-district', characters: [],
                    imageUrl: 'https://raw.githubusercontent.com/nancywang3641/sound-files/main/aseets/location_img/C區_市立教育語盟小學.jpeg',
                    desc: 'C 區的大學與職校聚集地，宿舍、平價餐廳、影印店。萊特、羅德、天凌、盧卡斯的日常，上課日白天有人，晚上散在夜市。',
                    regulars: ['許萊特', '羅德·洛爾德', '雲天凌', '盧卡斯·貝爾德', '白星澤'] },
                'Residential_Zone': { sceneId: 'C_Residential_Zone', name: '老公寓', icon: '🏘️', shortName: '老公寓', className: 'facility-residential-zone', characters: [],
                    imageUrl: 'https://raw.githubusercontent.com/nancywang3641/sound-files/main/aseets/location_img/C區_C-Ring_生活住宅群.jpeg',
                    desc: 'C 區的老舊公寓與小型公寓，月租便宜。彥庭、萊特住這裡；肯特家那棟低調的聯排別墅也在 C 區 Horizon。',
                    regulars: ['陳彥庭', '許萊特', '喬納森·肯特', '肯斯頓·肯特'] },
            }
        },
        'D': {
            name: 'Ivory 象牙高地',
            background: 'https://raw.githubusercontent.com/nancywang3641/sound-files/main/aseets/char_home/D%E5%8D%80_%E8%B1%A1%E7%89%99%E9%AB%98%E5%9C%B0.jpg',
            facilities: {
                'Vigil_Spire': { sceneId: 'D_Vigil_Spire', name: '守望塔醫院', icon: '🗼', shortName: '守望塔', className: 'facility-vigil', characters: [],
                    imageUrl: 'https://raw.githubusercontent.com/nancywang3641/sound-files/main/aseets/location_img/D區_VigilSpire_守塔.jpeg',
                    desc: '貝爾德家的私人頂級醫院，三十層，日費五萬起。豪門看病、療養、做見不得人的檢查都在這；亞德里安與西奧多的手術室。',
                    regulars: ['亞德里安·貝爾德', '西奧多·貝爾德', '各家族成員'] },
                'Black_Obsidian': { sceneId: 'D_Black_Obsidian', name: '黑曜拍賣會', icon: '🎯', shortName: '拍賣會', className: 'facility-black-obsidian', characters: [],
                    imageUrl: 'https://raw.githubusercontent.com/nancywang3641/sound-files/main/aseets/location_img/D區_黑曜拍賣會.jpeg',
                    desc: '月度高端拍賣，十萬保證金，須蓋雲紋印章才開拍；私人美術館的展覽也在同一棟。維斯頓主辦、雲家鑑定、各家在這裡較勁面子。',
                    regulars: ['雲震海', '雲天闊', '奧斯汀·維斯頓', '艾琳娜·維斯頓', '白梓妍'] },
                'Sky_Dome_Port': { sceneId: 'D_Sky_Dome_Port', name: '天穹港機場', icon: '🚁', shortName: '機場', className: 'facility-sky-dome', characters: [],
                    imageUrl: 'https://raw.githubusercontent.com/nancywang3641/sound-files/main/aseets/location_img/D區_SkyDome_Port_Extension.jpeg',
                    desc: '私人機場，四條跑道，海關簡化。家族私人飛機停這裡；出國、巡演、留學都從這裡走，也是「有人回來了」的消息傳出的地方。',
                    regulars: ['費利克斯·貝爾德', '各家族成員'] },
                'Platinum_Promenade': { sceneId: 'D_Platinum_Promenade', name: '白金長廊', icon: '💎', shortName: '長廊', className: 'facility-platinum', characters: [],
                    imageUrl: 'https://raw.githubusercontent.com/nancywang3641/sound-files/main/aseets/char_home/D%E5%8D%80_%E8%B1%A1%E7%89%99%E9%AB%98%E5%9C%B0.jpg',
                    desc: 'D 區的高端購物長廊，午後到傍晚是夫人與名媛的社交場，誰跟誰逛街本身就是消息。',
                    regulars: ['艾薇', '卡蜜拉·洛爾德', '林婉如', '莉安娜·維斯頓'] },
                'Diamond_Marina': { sceneId: 'D_Diamond_Marina', name: '鑽石遊艇碼頭', icon: '🛥️', shortName: '遊艇碼頭', className: 'facility-diamond', characters: [],
                    imageUrl: 'https://raw.githubusercontent.com/nancywang3641/sound-files/main/aseets/char_home/D%E5%8D%80_%E8%B1%A1%E7%89%99%E9%AB%98%E5%9C%B0.jpg',
                    desc: '家族遊艇停泊處，週末與夏夜有遊艇派對。放養群混進去的那種場合，也是雷蒙談生意不留紀錄的地方。',
                    regulars: ['雷蒙·蘭開斯特', '伊萊·蘭開斯特', '費利克斯·貝爾德', '白星澤'] },
                'Noble_Social_Club': { sceneId: 'D_Noble_Social_Club', name: '貴族社交會所', icon: '🍷', shortName: '會所', className: 'facility-noble', characters: [],
                    imageUrl: 'https://raw.githubusercontent.com/nancywang3641/sound-files/main/aseets/char_home/D%E5%8D%80_%E8%B1%A1%E7%89%99%E9%AB%98%E5%9C%B0.jpg',
                    desc: '會所、騎士俱樂部、翡翠高爾夫在同一個園區。家主們私下見面、不在會議桌上談的事在這裡談；喬納森的主場。',
                    regulars: ['各家家主', '喬納森·肯特'] },
                'Ivory_High_School': { sceneId: 'D_Ivory_High_School', name: '象牙學園', icon: '🏫', shortName: '學園', className: 'facility-ivory-school', characters: [],
                    imageUrl: 'https://raw.githubusercontent.com/nancywang3641/sound-files/main/aseets/location_img/D區_象牙國際高中.jpeg',
                    desc: '象牙小學到高中一條龍，加上皇家藝術學院，年學費三十到五十萬。豪門子弟的學校，家長日比董事會還政治。',
                    regulars: ['陸鳴野', '盧卡斯·貝爾德（畢業生）', '白星澤（畢業生）'] },
                'Manor_District': { sceneId: 'D_Manor_District', name: '十家老宅', icon: '🏰', shortName: '老宅', className: 'facility-manor-district', characters: [],
                    imageUrl: 'https://raw.githubusercontent.com/nancywang3641/sound-files/main/aseets/location_img/D區_雷伊_隱私海濱別墅.jpeg',
                    desc: '十家的老宅都在 D 區山上：主府、堡苑、光府、石堡、清館、舞館、雲頂府、雲府等。家宴、回家、聯姻、族會全在這裡發生；沒 D 區 ID 連門口的路都進不去。',
                    regulars: ['十家全員'] },
            }
        },
        'E': {
            name: 'Spirehollow 空塔街坊',
            background: 'https://raw.githubusercontent.com/nancywang3641/sound-files/main/aseets/char_home/E%E5%8D%80_%E7%A9%BA%E5%A1%94%E8%A1%97%E5%9D%8A.jpg',
            facilities: {
                'Wreckspire': { sceneId: 'E_Wreckspire', name: '殘塔', icon: '🗗️', shortName: '殘塔', className: 'facility-wreckspire', characters: [],
                    imageUrl: 'https://raw.githubusercontent.com/nancywang3641/sound-files/main/aseets/location_img/E區_Wreckspire.jpeg',
                    desc: '八公頃的廢棄街區，十幾棟坍塌建築。底層是流浪者聚落，高層是探險與跑酷的地方；羅德在這摔過車。',
                    regulars: ['黎昂·維斯頓', 'Zephyr Locke', '羅德·洛爾德'] },
                'Crimson_Cellar': { sceneId: 'E_Crimson_Cellar', name: '深紅窖', icon: '🍷', shortName: '深紅窖', className: 'facility-crimson-cellar-d', characters: [],
                    imageUrl: 'https://raw.githubusercontent.com/nancywang3641/sound-files/main/aseets/location_img/E區_Crimson_Cellar_深紅窖.jpeg',
                    desc: '防空洞改的地下酒吧，午夜後營業，賣烈酒與消息。黎昂的情報線在這裡接頭；暗門通往地下三十米的冥根層。',
                    regulars: ['黎昂·維斯頓', 'Zephyr Locke', '維克托·克特羅斯', '白羽霜'] },
                'Shadow_Furnace': { sceneId: 'E_Shadow_Furnace', name: '鏽蝕中樞', icon: '🔥', shortName: '中樞', className: 'facility-shadow-furnace', characters: [],
                    imageUrl: 'https://raw.githubusercontent.com/nancywang3641/sound-files/main/aseets/location_img/E區_ShadowFurnace_影熔爐.jpeg',
                    desc: 'E 區地下的中心廣場，巨大廢棄渦輪機改的，非法能源私接點。維克托的地盤，E 區黑市全部收在這裡；白天也暗，靠私接的燈。',
                    regulars: ['維克托·克特羅斯', '白羽霜', '馬爾科的人', '黎昂·維斯頓'] },
                'Glitch_Dome': { sceneId: 'E_Glitch_Dome', name: '錯位圓頂', icon: '⚡', shortName: '圓頂', className: 'facility-glitch-dome', characters: [],
                    imageUrl: 'https://raw.githubusercontent.com/nancywang3641/sound-files/main/aseets/location_img/E區_GlitchDome_錯位圓頂.jpeg',
                    desc: '訊號混亂的圓頂建築，駭客聚會地，幻神經核的暗網節點與沉默庫的密談室都在裡面。丹以前常來，現在只在有事時出現。',
                    regulars: ['丹尼爾·卡萊爾', '馬庫斯·卡萊爾', '柴郡（隱）'] },
                'Null_Sanctuary': { sceneId: 'E_Null_Sanctuary', name: '無號庇所', icon: '🏚️', shortName: '庇所', className: 'facility-null', characters: [],
                    imageUrl: 'https://raw.githubusercontent.com/nancywang3641/sound-files/main/aseets/location_img/E區_NullSanctuary_無號庇所.jpeg',
                    desc: 'E 區的收容所，沒有城市 ID 的人住這裡：移工、逃債的、不想被找到的。彥庭會送吃的來，雷諾偶爾在這裡修東西。',
                    regulars: ['陳彥庭', '雷諾·克特羅斯', '無號的人'] },
                'Pulse_Street': { sceneId: 'E_Pulse_Street', name: '脈動街', icon: '💓', shortName: '脈動街', className: 'facility-pulse-street', characters: [],
                    imageUrl: 'https://raw.githubusercontent.com/nancywang3641/sound-files/main/aseets/location_img/E區_PulseStreet_脈動街.jpeg',
                    desc: 'E 區的市集，二手電子、零件、來路不明的物資，白天就開。羅德找零件、丹找硬體、天凌在這裡替人鑑定古物賺外快，不留收據。',
                    regulars: ['羅德·洛爾德', '丹尼爾·卡萊爾', '雲天凌'] },
                'Silent_Haven': { sceneId: 'E_Silent_Haven', name: '靜隱旅館', icon: '🤫', shortName: '靜隱', className: 'facility-silent', characters: [],
                    imageUrl: 'https://raw.githubusercontent.com/nancywang3641/sound-files/main/aseets/location_img/E區_SilentHaven_靜隱.jpeg',
                    desc: '不問名字的旅館，現金付、沒有監視器。藏身、躲人、等風頭過的地方；雷諾住過。',
                    regulars: ['雷諾·克特羅斯', '被追的人'] },
                'Tin_City': { sceneId: 'E_Tin_City', name: '鐵皮城', icon: '🏚️', shortName: '鐵皮城', className: 'facility-tin', characters: [],
                    imageUrl: 'https://raw.githubusercontent.com/nancywang3641/sound-files/main/aseets/char_home/E%E5%8D%80_%E7%A9%BA%E5%A1%94%E8%A1%97%E5%9D%8A.jpg',
                    desc: '違章建築疊成的移工聚落，方言、廟口、家鄉菜。E 區大半人口住這裡，傍晚下工後最熱鬧；不是廢土，是有人過日子的地方。',
                    regulars: ['移工 NPC', '陳彥庭', '黎昂·維斯頓'] },
                'Mod_Workshop': { sceneId: 'E_Mod_Workshop', name: '改造作坊', icon: '🔧', shortName: '作坊', className: 'facility-mod', characters: [],
                    imageUrl: 'https://raw.githubusercontent.com/nancywang3641/sound-files/main/aseets/char_home/E%E5%8D%80_%E7%A9%BA%E5%A1%94%E8%A1%97%E5%9D%8A.jpg',
                    desc: '機車改裝、機械修理，後面一間是無照義體與黑診所。黎昂的車、羅德的怪機械都出自這裡；受傷不想進醫院的人也來這。',
                    regulars: ['黎昂·維斯頓', '羅德·洛爾德', 'Zephyr Locke', '雷諾·克特羅斯'] },
            }
        },
        'F': {
            name: 'Aetherdock 蒸穹港域',
            background: '',   // 區底圖待補（素材清單 MAP-ZF）
            facilities: {
                'Container_Dock': { sceneId: 'F_Container_Dock', name: '貨櫃碼頭', icon: '🚢', shortName: '碼頭', className: 'facility-container-dock', characters: [],
                    imageUrl: '',
                    desc: '二十個泊位、日均五千貨櫃，城的進出口。走真實航線，海關與白家安保都盯著；走私與查緝的戲在這裡。清晨最忙。',
                    regulars: ['白墨塵的人', '海關', '雷諾·克特羅斯'] },
                'Aether_Towers': { sceneId: 'F_Aether_Towers', name: '以太塔群', icon: '🗼', shortName: '塔群', className: 'facility-aether-towers', characters: [],
                    imageUrl: '',
                    desc: '五座 120 到 180 米的塔，港口管制與通訊中繼。F 區的地標，看得到但很少有人真的進去。',
                    regulars: [] },
                'Harbor_Loft': { sceneId: 'F_Harbor_Loft', name: '港口 Loft', icon: '🏭', shortName: 'Loft', className: 'facility-harbor-loft', characters: [],
                    imageUrl: '',
                    desc: '工業 Loft 住宅，港口工人、技術員、藝術家混住。白則住這裡，客廳角落有艾迪的懶人沙發；盧卡斯每週固定打一通電話來。',
                    regulars: ['白則·貝爾德', '艾迪·克特羅斯', '盧卡斯·貝爾德'] },
                'Dock_Canteen': { sceneId: 'F_Dock_Canteen', name: '港邊食堂', icon: '🍜', shortName: '食堂', className: 'facility-dock-canteen', characters: [],
                    imageUrl: '',
                    desc: '碼頭工人與技工的食堂，清晨四點開。雷諾接散單時在這吃早餐，白則來買咖啡，羅德來這裡找機械師傅。',
                    regulars: ['雷諾·克特羅斯', '羅德·洛爾德', '白則·貝爾德'] },
            }
        },
        'G': {
            name: 'Mirage Crown 幻冠天城',
            background: '',   // 區底圖待補（素材清單 MAP-ZG）
            facilities: {
                'Silver_Tier': { sceneId: 'G_Silver_Tier', name: '白銀層', icon: '🎰', shortName: '白銀層', className: 'facility-silver-tier', characters: [],
                    imageUrl: '',
                    desc: '平民賭場，百元起賭，兩千台老虎機。大學生與遊客的樓層，白星澤在這裡拍 Vlog，羅德輸過生活費。',
                    regulars: ['羅德·洛爾德', '許萊特', '白星澤'] },
                'Gold_Tier': { sceneId: 'G_Gold_Tier', name: '黃金層', icon: '🃏', shortName: '黃金層', className: 'facility-gold-tier', characters: [],
                    imageUrl: '',
                    desc: '高級賭場與主題廳，千元到百萬的賭注。雷蒙豪賭、宗澤下注、雷伊陪客戶的地方。',
                    regulars: ['雷蒙·蘭開斯特', '林宗澤', '雷伊·洛爾德'] },
                'Diamond_VIP': { sceneId: 'G_Diamond_VIP', name: '鑽石層 VIP', icon: '💎', shortName: 'VIP', className: 'facility-diamond-vip', characters: [],
                    imageUrl: '',
                    desc: '入場十萬的頂層，豪賭套房裡簽的不只賭約，還有軍火、情報、政治協議。白梓妍的地盤，各家私密交易的中立場。',
                    regulars: ['白梓妍', '白致遠', '馬爾科·克特羅斯', '克里斯·克特羅斯'] },
                'Sky_Palace_Hotel': { sceneId: 'G_Sky_Palace_Hotel', name: '天宮酒店', icon: '🏨', shortName: '酒店', className: 'facility-sky-palace-hotel', characters: [],
                    imageUrl: '',
                    desc: '五星酒店五百間房，一晚兩千到五萬。密會、過夜、躲記者；煦陽與卡門的場子。',
                    regulars: ['林煦陽', '卡門·羅斯', '費利克斯·貝爾德'] },
                'Entertainment_Hub': { sceneId: 'G_Entertainment_Hub', name: '娛樂中樞', icon: '🎭', shortName: '娛樂', className: 'facility-entertainment-hub', characters: [],
                    imageUrl: '',
                    desc: '星光劇院、天鵝絨酒廊、午夜歌舞廳、回響酒吧街。旭南在這裡駐唱過，瓦倫丁的秀在這裡辦。',
                    regulars: ['林旭南', '瓦倫丁·聖詹姆斯', '艾琳娜·維斯頓'] },
                'Underground_Ring': { sceneId: 'G_Underground_Ring', name: '地下拳賽', icon: '🥊', shortName: '拳賽', className: 'facility-underground-ring', characters: [],
                    imageUrl: '',
                    desc: 'G 區地下的無規則拳賽，下注不設上限。宗澤來這裡放鬆，黎昂上過場，維克托的人管秩序。',
                    regulars: ['林宗澤', '黎昂·維斯頓', '維克托·克特羅斯'] },
            }
        },
    };

    // 掛載到全局
    window.AUREALIS_DATA = {
        zones: AUREALIS_DB,

        // 獲取指定區域的數據
        getZone: function(zoneId) {
            return AUREALIS_DB[zoneId];
        },

        // 獲取所有區域ID
        getZoneIds: function() {
            return Object.keys(AUREALIS_DB);
        }
    };

    console.log(`[AurealisData] 已加載 ${Object.keys(AUREALIS_DB).length} 個區域配置`);
})();
